import axios from "axios";
import FormData from "form-data";
import { AuditReport } from "./types";

const PINATA_JWT = process.env.PINATA_JWT;
const PINATA_API_KEY = process.env.PINATA_API_KEY;
const PINATA_SECRET_API_KEY = process.env.PINATA_SECRET_API_KEY;

const getHeaders = () => {
    if (PINATA_JWT) {
        return { Authorization: `Bearer ${PINATA_JWT}` };
    }
    if (PINATA_API_KEY && PINATA_SECRET_API_KEY) {
        return {
            pinata_api_key: PINATA_API_KEY,
            pinata_secret_api_key: PINATA_SECRET_API_KEY
        };
    }
    throw new Error("Missing Pinata API credentials in environment variables.");
};

/**
 * Uploads a file buffer (e.g., the PDF report) to IPFS via Pinata.
 * Returns the IPFS URI (ipfs://CID).
 */
export async function uploadFileToIPFS(fileBuffer: Buffer, filename: string): Promise<string> {
    const formData = new FormData();
    formData.append("file", fileBuffer, { filename });

    const response = await axios.post("https://api.pinata.cloud/pinning/pinFileToIPFS", formData, {
        maxBodyLength: Infinity,
        headers: {
            ...getHeaders(),
            ...formData.getHeaders(),
        },
    });

    return `ipfs://${response.data.IpfsHash}`;
}

/**
 * Uploads ERC721 standard JSON metadata to IPFS via Pinata.
 * Returns the IPFS URI (ipfs://CID).
 */
export async function uploadMetadataToIPFS(report: AuditReport, pdfIpfsUri: string): Promise<string> {
    const metadata = {
        name: `AegisHBAR Audit: ${report.contractName}`,
        description: `Automated smart contract security audit report for ${report.contractName} generated by AegisHBAR.`,
        image: pdfIpfsUri, // We use the PDF as the primary visual asset
        type: "application/pdf",
        properties: {
            sourceHash: report.sourceHash,
            riskScore: report.overallRiskScore,
            criticalFindings: report.summary.critical,
            highFindings: report.summary.high,
            mediumFindings: report.summary.medium,
            lowFindings: report.summary.low,
            timestamp: report.timestamp
        }
    };

    const response = await axios.post("https://api.pinata.cloud/pinning/pinJSONToIPFS", metadata, {
        headers: {
            ...getHeaders(),
            "Content-Type": "application/json"
        }
    });

    return `ipfs://${response.data.IpfsHash}`;
}
